### ISSUE TITLE
auth failed on Heroku

### ISSUE THREAD

**Issue by kbowerma** [mongolab/hello-mongoose#4]
Does this example still work on Heroku?   When I run it locally it works fun but when I deploy it to Heroku I get an Auth failed:

```
ERROR connecting to: mongodb://xxx:yyy@ds047782.mongolab.com:47782/xxx. MongoError: auth failed  
```

I took out the login and password of course.

I tried to connect with my local mongo client and got the same error then upgrade my mongo shell from: 2.6.4_1  to  3.0.7 and it worked fine.   I think I recall that mongolab upgraded to 3.0 and all drivers need to be upgraded too.

However I see in package.json that you are using mongoose 3.8.15 so I am a little confused

**Comment by chrisckchang** [comment]
great catch, thanks! didn't see the PR until after I committed d873461a5cae8c914b4385f6259b2d7a83e164e3. should work now!

**Comment by kbowerma** [comment]
thanks man
