### ISSUE TITLE
MongoError: auth failed

### ISSUE THREAD

**Issue by fbukevin** [mongolab/hello-mongoose#6]
Did mongolab change the authentication method for using mongoose?

I followed the official documentation using uri string, that is, `mongodb://dbuser:dbpass@host:port/db`, to connection to mongodb server on mongolab in my app's db configurartion. But I always got the following error:

`{ [MongoError: auth failed] name: 'MongoError', ok: 0, errmsg: 'auth failed', code: 18 }`

I'm pretty sure that I used valid db username and db password created in my mongolab console. And before mongolab announced to upgrade in past few month, my heroku application still works.

I also found the heroku "Application Error" page shows up in [hello-mongoose](http://hello-mongoose.herokuapp.com/).

<img width="748" alt="ae" src="https://cloud.githubusercontent.com/assets/4548874/10789145/9aa54988-7db6-11e5-9e2a-14a8b586a0ee.png">

**Comment by chrisckchang** [comment]
Hi,

Your database is now running with the SCRAM-SHA-1 authentication schema. This commit d873461a5cae8c914b4385f6259b2d7a83e164e3 shows the changes you'll need to make to your project to get it to run properly again.

Thanks for the heads up about the "Application Error" page, I'll make sure that's fixed.

**Comment by fbukevin** [comment]
Thanks chris, With updating mongoose version in package.json, my app work fine to connect to MongoLab server.
